language: perl
env:
  - RO_IMPLEMENTATION=PP
  - RO_IMPLEMENTATION=XS
perl:
  - "5.6.2"
  - "5.8.1"
  - "5.8.9"
  - "5.10.0"
  - "5.10.1"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "blead"
matrix:
  include:
    - perl: 5.18.2
      env: COVERAGE=1 RO_IMPLEMENTATION=PP
before_install:
  - git clone git://github.com/haarg/perl-travis-helper
  - source perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --toolchain
  - cpan-install --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - prove -l $(test-dirs)
after_success:
  - coverage-report
